services:
  optimum-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    restart: unless-stopped
    networks:
      - gateway_cluster
    ports:
      - "33212:33212/tcp"
      - "33213:33213/udp"
      - "48123:48123/tcp"
    volumes:
      - "./config:/app/config:ro"
      - "./mump2p/data/mump2p/:/tmp/mump2p"
      - "./mump2p/data/libp2p/:/tmp/libp2p"
    command: ["-config=/app/config/app_conf.yml"]

networks:
  gateway_cluster:
