// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: getoptimum/optimum_gateway/service/stream/v1/stream.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockStreamService_Subscribe_FullMethodName = "/getoptimum.optimum_gateway.service.stream.v1.BlockStreamService/Subscribe"
)

// BlockStreamServiceClient is the client API for BlockStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BlockStreamService streams decoded beacon-block observations to consumers (ADR-0011).
type BlockStreamServiceClient interface {
	// Subscribe opens a read-only server stream of block observations.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockEvent], error)
}

type blockStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockStreamServiceClient(cc grpc.ClientConnInterface) BlockStreamServiceClient {
	return &blockStreamServiceClient{cc}
}

func (c *blockStreamServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlockStreamService_ServiceDesc.Streams[0], BlockStreamService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, BlockEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockStreamService_SubscribeClient = grpc.ServerStreamingClient[BlockEvent]

// BlockStreamServiceServer is the server API for BlockStreamService service.
// All implementations must embed UnimplementedBlockStreamServiceServer
// for forward compatibility.
//
// BlockStreamService streams decoded beacon-block observations to consumers (ADR-0011).
type BlockStreamServiceServer interface {
	// Subscribe opens a read-only server stream of block observations.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[BlockEvent]) error
	mustEmbedUnimplementedBlockStreamServiceServer()
}

// UnimplementedBlockStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockStreamServiceServer struct{}

func (UnimplementedBlockStreamServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[BlockEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedBlockStreamServiceServer) mustEmbedUnimplementedBlockStreamServiceServer() {}
func (UnimplementedBlockStreamServiceServer) testEmbeddedByValue()                            {}

// UnsafeBlockStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockStreamServiceServer will
// result in compilation errors.
type UnsafeBlockStreamServiceServer interface {
	mustEmbedUnimplementedBlockStreamServiceServer()
}

func RegisterBlockStreamServiceServer(s grpc.ServiceRegistrar, srv BlockStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedBlockStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockStreamService_ServiceDesc, srv)
}

func _BlockStreamService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockStreamServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, BlockEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockStreamService_SubscribeServer = grpc.ServerStreamingServer[BlockEvent]

// BlockStreamService_ServiceDesc is the grpc.ServiceDesc for BlockStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "getoptimum.optimum_gateway.service.stream.v1.BlockStreamService",
	HandlerType: (*BlockStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _BlockStreamService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "getoptimum/optimum_gateway/service/stream/v1/stream.proto",
}
