// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: getoptimum/optimum_gateway/service/stream/v1/stream.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscribeRequest selects the payload mode and topics for a subscription.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`     // "metadata" (default) or "raw"
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"` // only "beacon_block" is supported in v1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// BlockEvent is one block observation, or a lagged control signal after
// buffer overflow (fields mirror the streamhub hub type).
type BlockEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Slot           uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ProposerIndex  uint64                 `protobuf:"varint,2,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty"`
	ParentRoot     []byte                 `protobuf:"bytes,3,opt,name=parent_root,json=parentRoot,proto3" json:"parent_root,omitempty"`
	StateRoot      []byte                 `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	BlockSizeBytes uint64                 `protobuf:"varint,5,opt,name=block_size_bytes,json=blockSizeBytes,proto3" json:"block_size_bytes,omitempty"`
	Topic          string                 `protobuf:"bytes,6,opt,name=topic,proto3" json:"topic,omitempty"`
	Source         string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	ReceivedAtMs   int64                  `protobuf:"varint,8,opt,name=received_at_ms,json=receivedAtMs,proto3" json:"received_at_ms,omitempty"`
	GatewayId      string                 `protobuf:"bytes,9,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	ForkDigest     string                 `protobuf:"bytes,10,opt,name=fork_digest,json=forkDigest,proto3" json:"fork_digest,omitempty"`
	Stale          bool                   `protobuf:"varint,11,opt,name=stale,proto3" json:"stale,omitempty"`
	Raw            []byte                 `protobuf:"bytes,12,opt,name=raw,proto3" json:"raw,omitempty"`          // present only in raw mode
	Lagged         bool                   `protobuf:"varint,13,opt,name=lagged,proto3" json:"lagged,omitempty"`   // true on a control frame after overflow
	Dropped        uint64                 `protobuf:"varint,14,opt,name=dropped,proto3" json:"dropped,omitempty"` // cumulative dropped count, set when lagged
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockEvent) Reset() {
	*x = BlockEvent{}
	mi := &file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockEvent) ProtoMessage() {}

func (x *BlockEvent) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockEvent.ProtoReflect.Descriptor instead.
func (*BlockEvent) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_rawDescGZIP(), []int{1}
}

func (x *BlockEvent) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *BlockEvent) GetProposerIndex() uint64 {
	if x != nil {
		return x.ProposerIndex
	}
	return 0
}

func (x *BlockEvent) GetParentRoot() []byte {
	if x != nil {
		return x.ParentRoot
	}
	return nil
}

func (x *BlockEvent) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BlockEvent) GetBlockSizeBytes() uint64 {
	if x != nil {
		return x.BlockSizeBytes
	}
	return 0
}

func (x *BlockEvent) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *BlockEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BlockEvent) GetReceivedAtMs() int64 {
	if x != nil {
		return x.ReceivedAtMs
	}
	return 0
}

func (x *BlockEvent) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *BlockEvent) GetForkDigest() string {
	if x != nil {
		return x.ForkDigest
	}
	return ""
}

func (x *BlockEvent) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *BlockEvent) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *BlockEvent) GetLagged() bool {
	if x != nil {
		return x.Lagged
	}
	return false
}

func (x *BlockEvent) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

var File_getoptimum_optimum_gateway_service_stream_v1_stream_proto protoreflect.FileDescriptor

const file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_rawDesc = "" +
	"\n" +
	"9getoptimum/optimum_gateway/service/stream/v1/stream.proto\x12,getoptimum.optimum_gateway.service.stream.v1\">\n" +
	"\x10SubscribeRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\"\x9f\x03\n" +
	"\n" +
	"BlockEvent\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12%\n" +
	"\x0eproposer_index\x18\x02 \x01(\x04R\rproposerIndex\x12\x1f\n" +
	"\vparent_root\x18\x03 \x01(\fR\n" +
	"parentRoot\x12\x1d\n" +
	"\n" +
	"state_root\x18\x04 \x01(\fR\tstateRoot\x12(\n" +
	"\x10block_size_bytes\x18\x05 \x01(\x04R\x0eblockSizeBytes\x12\x14\n" +
	"\x05topic\x18\x06 \x01(\tR\x05topic\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12$\n" +
	"\x0ereceived_at_ms\x18\b \x01(\x03R\freceivedAtMs\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\t \x01(\tR\tgatewayId\x12\x1f\n" +
	"\vfork_digest\x18\n" +
	" \x01(\tR\n" +
	"forkDigest\x12\x14\n" +
	"\x05stale\x18\v \x01(\bR\x05stale\x12\x10\n" +
	"\x03raw\x18\f \x01(\fR\x03raw\x12\x16\n" +
	"\x06lagged\x18\r \x01(\bR\x06lagged\x12\x18\n" +
	"\adropped\x18\x0e \x01(\x04R\adropped2\x9e\x01\n" +
	"\x12BlockStreamService\x12\x87\x01\n" +
	"\tSubscribe\x12>.getoptimum.optimum_gateway.service.stream.v1.SubscribeRequest\x1a8.getoptimum.optimum_gateway.service.stream.v1.BlockEvent0\x01B=Z;github.com/getoptimum/optimum-gateway/pkg/service/stream/v1b\x06proto3"

var (
	file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_rawDescOnce sync.Once
	file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_rawDescData []byte
)

func file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_rawDescGZIP() []byte {
	file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_rawDescOnce.Do(func() {
		file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_rawDesc), len(file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_rawDesc)))
	})
	return file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_rawDescData
}

var file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: getoptimum.optimum_gateway.service.stream.v1.SubscribeRequest
	(*BlockEvent)(nil),       // 1: getoptimum.optimum_gateway.service.stream.v1.BlockEvent
}
var file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_depIdxs = []int32{
	0, // 0: getoptimum.optimum_gateway.service.stream.v1.BlockStreamService.Subscribe:input_type -> getoptimum.optimum_gateway.service.stream.v1.SubscribeRequest
	1, // 1: getoptimum.optimum_gateway.service.stream.v1.BlockStreamService.Subscribe:output_type -> getoptimum.optimum_gateway.service.stream.v1.BlockEvent
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_init() }
func file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_init() {
	if File_getoptimum_optimum_gateway_service_stream_v1_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_rawDesc), len(file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_goTypes,
		DependencyIndexes: file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_depIdxs,
		MessageInfos:      file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_msgTypes,
	}.Build()
	File_getoptimum_optimum_gateway_service_stream_v1_stream_proto = out.File
	file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_goTypes = nil
	file_getoptimum_optimum_gateway_service_stream_v1_stream_proto_depIdxs = nil
}
