#!/usr/bin/env python3
"""Generate the mid-scale stack: a compose file for N gateways and the config it is served.

Two files are written, both git-ignored, both regenerated by every run.sh:

  stack.yml           the compose project: control plane, N x (rlnc-server +
                      gateway), publisher
  served-config.json  the DynamicConfig nginx serves, which is
                      dynamic-config.json with the swept knobs applied

The tier exists to move the peer count, so the compose file cannot be a
committed constant: every gateway needs its own shared-memory volume, its own
coder sidecar and its own published port, none of which `docker compose --scale`
can give it.

Usage:
  gen-stack.py [--gateways 12] [--base-port 48151] [--lanes 20]
               [--forward-threshold 0.75] [--shard-factor 16]
               [--publisher-multiplier 2.5] [--mesh-degree 6]
"""

import argparse
import json
import math
import os
import sys

# One shared-memory lane is 16777240 bytes. The demo sizes its tmpfs at 1.6x the
# lanes' own footprint and that headroom is what the coder wants, so keep the
# ratio rather than the absolute number: the lane count is a knob here.
LANE_BYTES = 16777240
SHM_HEADROOM = 1.6

CLUSTER_ID = "datagram-scale"
IMAGE = "optimum-gateway-datagram-scale:local"

# Fixed test identities, copied from the five-gateway stack: the publisher dials
# gateway1 by peer ID without discovery and gateway1 allowlists the publisher.
GATEWAY1_CL_PEER_ID = "12D3KooWEDTWcWiackMyvjvAUut5kk9acyZUnNEuoALFrs7fWH41"
PUBLISHER_PEER_ID = "12D3KooWPDjNxSEBqze1kBvHjwoqFFvmiG7VCq2VVC3X5rgDJRPr"

HEADER = """# GENERATED by gen-stack.py -- edit that, not this.
#
# {n} gateways carrying RLNC traffic over the encrypted UDP datagram data plane,
# sized so that no node receives enough of a generation directly from the
# publisher to open its own forwarding gate. See README.md.
#
# Bring this up with run.sh, not `docker compose up`: peers are fetched from the
# bootstrap exactly once at startup and never re-fetched, so the order gateways
# start in is what decides the topology.

x-gateway-env: &gateway-env
  # Pure Go resolver: the C resolver would consult a host nsswitch this image
  # does not have, and every service address here is a compose DNS name.
  GODEBUG: netdns=go
  # Must appear in the mock's OPT_BENCH_AUTH_CLUSTER_IDS and be identical on
  # every gateway. A mismatch is rejected inside the mump2p handshake and shows
  # up as a mesh with no edges, never as an auth error.
  OPT_GATEWAY_CLUSTER_ID: {cluster}
  # Bootstrap traffic goes through the config proxy so the run's DynamicConfig
  # is served on the config path; auth goes direct, because the gateway pins the
  # JWT issuer to this URL verbatim and the mock mints that exact string.
  OPT_REMOTE_BOOTSTRAP_URL: http://configproxy:48124
  OPT_REMOTE_AUTH_URL: http://bootstrap:48124
  OPT_ENABLE_AUTH: "true"
  # The mock ignores the value but it must be non-empty: an empty key disables
  # the auth manager, after which there are no claims, the chain ID is empty and
  # the gateway fatals in InitRuntime.
  OPT_API_KEY: {cluster}-key
  # Under /tmp because the container runs as uid 10001.
  OPT_JWKS_CACHE_PATH: /tmp/jwks.json
  OPT_ENABLE_TELEMETRY: "true"
  OPT_TELEMETRY_PORT: "48123"
  OPT_AGENT_LIB_P2P_PORT: "33212"
  OPT_AGENT_MUMP2P_PORT: "33213"
  OPT_LOG_LEVEL: info
  OPT_REMOTE_PUSH_ENABLE: "false"
  OPT_SHM_LANES: "{lanes}"
  OPT_DATAGRAM_ENABLE: ${{SCALE_DATAGRAM_ENABLE:-true}}
  OPT_DATAGRAM_LISTEN_ADDR: 0.0.0.0:4101
  # OPT_DATAGRAM_MAX_PAYLOAD is deliberately unset: the 1200 byte transport
  # default is what the shard size is derived from, and report.py checks the
  # derived number.
  OPT_OTEL_ENABLE: "true"
  # host:port, no scheme; OTLP over HTTP.
  OPT_OTEL_ENDPOINT: otel-collector:4318
  OPT_OTEL_INSECURE: "true"
  OPT_OTEL_SAMPLE_RATIO: "1.0"

x-gateway: &gateway
  image: {image}
  entrypoint: ["/usr/local/bin/gateway-entrypoint.sh"]
  # Same uid as the rlnc-server sidecars, so both ends of the shared-memory
  # lanes are owned by one user.
  user: "10001:10001"
  networks: [scale]
  restart: "no"
  # The gateway probes public HTTP endpoints to learn the address it registers
  # with the bootstrap. Pointing them at localhost makes every probe fail
  # immediately, so it falls back to interface inspection and registers its own
  # container address, which is the only address its peers can reach it on.
  extra_hosts:
    - "cloudflare.com:127.0.0.1"
    - "checkip.amazonaws.com:127.0.0.1"
    - "bootstrap.getoptimum.io:127.0.0.1"
    - "raw.githubusercontent.com:127.0.0.1"

x-rlnc: &rlnc
  # Pinned: the coder and the gateway's mump2p-protocol share a shared-memory
  # wire format. Keep in step with RLNC_IMAGE_VERSION in the repo Makefile.
  image: getoptimum/rlnc-server:${{RLNC_IMAGE_VERSION:-v0.10.0}}
  user: "10001:10001"
  networks: [scale]
  restart: "no"

# {lanes} lanes of {lane_bytes} bytes need {lane_mib} MiB, so the size is set here rather
# than left to the 64 MiB default the daemon gives /dev/shm. {n} of these are
# created, for a {total_gib:.1f} GiB tmpfs ceiling and about {touched_gib:.1f} GiB actually
# touched; drop --lanes if that does not fit.
x-shm: &shm
  driver: local
  driver_opts:
    type: tmpfs
    device: tmpfs
    o: size={shm_mib}m,mode=1777

services:
  # One binary replacing optimum-auth, optimum-bootstrap and its Postgres:
  # registration, peer discovery, fork digest, the JWKS document and the JWT
  # mint. The issuer it stamps is http://bootstrap:48124, which is why this
  # service is named `bootstrap` and listens on that port.
  bootstrap:
    image: {image}
    entrypoint: ["/usr/local/bin/mock-bootstrap"]
    command: ["-addr", ":48124"]
    user: "10001:10001"
    networks: [scale]
    restart: "no"
    environment:
      GODEBUG: netdns=go
      OPT_BENCH_AUTH_CLUSTER_IDS: {cluster}
      # No synthetic seed peer: every gateway here is real and reachable, and a
      # seed pointing at an address that does not exist only burns dial budget
      # on nodes that dial exactly once.
      OPT_BENCH_SEED_DISABLE: "1"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:48124/healthz"]
      interval: 2s
      timeout: 2s
      retries: 15

  configproxy:
    image: nginx:1.27-alpine
    networks: [scale]
    restart: "no"
    # `z` relabels these for SELinux. Without it the container cannot read its
    # own config on an enforcing host, and the failure looks like a plain
    # permission bug. It is a no-op where SELinux is not in use.
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro,z"
      - "./served-config.json:/srv/served-config.json:ro,z"
    depends_on:
      bootstrap: {{condition: service_healthy}}
    # Probes the config path itself, not just the port. A config fetch that
    # 404s is not an error the gateway reports: it keeps its built-in defaults,
    # silently codes at k=4, and the run looks fine until delivery is measured.
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:48124/api/v1/hoodi/{cluster}/config"]
      interval: 2s
      timeout: 2s
      retries: 15

  otel-collector:
    image: otel/opentelemetry-collector:0.115.0
    command: ["--config=/etc/otel/config.yaml"]
    networks: [scale]
    restart: "no"
    volumes:
      - "./otel-collector.yaml:/etc/otel/config.yaml:ro,z"
    # The debug exporter prints every span, which is hundreds of MB at this node
    # count. journald (podman's default driver) rate-limits and would silently
    # drop spans, so pin a file driver with a cap far above the expected volume.
    logging:
      driver: json-file
      options:
        max-size: "4g"
        max-file: "2"
"""

RLNC_SERVICE = """
  rlnc{i}:
    <<: *rlnc
    command: ["--name=gw{i}-mump2p", "--lanes={lanes}", "--output-reclaim-after=5s"]
    volumes: ["shm{i}:/dev/shm"]
    # Lanes are created in order, so the last one existing means the whole set
    # is mapped and the gateway can attach.
    healthcheck:
      test: ["CMD-SHELL", "test -f /dev/shm/go_shm_rlnc_semaphore_gw{i}-mump2p_lane_{last_lane}"]
      interval: 2s
      timeout: 2s
      retries: 15
"""

GATEWAY_SERVICE = """
  gateway{i}:
    <<: *gateway
    environment:
      <<: *gateway-env
      OPT_GATEWAY_ID: {cluster}-gw{i}
      OPT_IDENTITY_LIBP2P_DIR: /tmp/gw{i}/libp2p
      OPT_IDENTITY_MUMP2P_DIR: /tmp/gw{i}/mump2p
      OPT_SHM_NAME: gw{i}-mump2p{extra_env}
    volumes: ["shm{i}:/dev/shm"]
    # Bound to loopback: an explicit interface keeps the published telemetry off
    # every other address on the host.
    ports: ["127.0.0.1:{port}:48123"]
    depends_on:
      rlnc{i}: {{condition: service_healthy}}
      bootstrap: {{condition: service_healthy}}
      configproxy: {{condition: service_healthy}}
      otel-collector: {{condition: service_started}}
"""

PUBLISHER_SERVICE = """
  # Real consensus-layer ingress: a libp2p gossipsub peer that completes the
  # eth2 status handshake with gateway1 and then publishes valid hoodi
  # beacon_block messages, exactly the way a production CL sidecar feeds the
  # gateway. Started last, by run.sh, once the topology has settled.
  publisher:
    image: {image}
    entrypoint: ["/usr/local/bin/bench-traffic"]
    user: "10001:10001"
    networks: [scale]
    restart: "no"
    command:
      - "-count=${{SCALE_MSG_COUNT:-8}}"
      # >= 12s: the gateway keys block tracking by slot and drops a block whose
      # slot is more than 3 slots from its own, so one block per slot it is.
      - "-rate=12s"
      - "-warmup=${{SCALE_WARMUP:-20s}}"
      - "-listen-port=33220"
      - "-msg-size=0"
    environment:
      GODEBUG: netdns=go
      OPT_BENCH_TARGET_ADDR: /dns4/gateway1/tcp/33212/p2p/{gw1_peer}
      OPT_BENCH_IDENTITY: /keys/publisher-cl.p2p.key
      # The gateway ignores any genesis override and always uses hoodi's, so the
      # publisher must stamp this exact epoch or every block it produces is
      # rejected as stale.
      OPT_GENESIS_TIME: "1742213400"

networks:
  scale:

volumes:
"""


def render(args):
    lane_mib = math.ceil(args.lanes * LANE_BYTES / (1024 * 1024))
    shm_mib = math.ceil(lane_mib * SHM_HEADROOM / 32) * 32
    parts = [HEADER.format(
        n=args.gateways,
        cluster=CLUSTER_ID,
        image=IMAGE,
        lanes=args.lanes,
        lane_bytes=LANE_BYTES,
        lane_mib=lane_mib,
        shm_mib=shm_mib,
        total_gib=args.gateways * shm_mib / 1024,
        touched_gib=args.gateways * lane_mib / 1024,
    )]

    for i in range(1, args.gateways + 1):
        parts.append(RLNC_SERVICE.format(i=i, lanes=args.lanes, last_lane=args.lanes - 1))

    for i in range(1, args.gateways + 1):
        # gateway1 is the publishing ingress: it holds a fixed CL identity so the
        # publisher can dial it by peer ID, and allowlists that publisher.
        extra = ""
        if i == 1:
            extra = (
                "\n      GW_KEY: gateway1-libp2p.p2p.key"
                f"\n      OPT_DIRECT_CL_PEERS: /dns4/publisher/tcp/33220/p2p/{PUBLISHER_PEER_ID}"
            )
        parts.append(GATEWAY_SERVICE.format(
            i=i, cluster=CLUSTER_ID, port=args.base_port + i - 1, extra_env=extra,
        ))

    parts.append(PUBLISHER_SERVICE.format(image=IMAGE, gw1_peer=GATEWAY1_CL_PEER_ID))
    for i in range(1, args.gateways + 1):
        parts.append(f"  shm{i}: {{<<: *shm}}\n")

    return "".join(parts), shm_mib, lane_mib


def served_config(args, base_path):
    with open(base_path, encoding="utf-8") as fh:
        cfg = json.load(fh)
    cfg["rlnc_shard_factor"] = args.shard_factor
    cfg["publisher_shard_multiplier"] = args.publisher_multiplier
    cfg["forward_shard_threshold"] = args.forward_threshold
    cfg["mesh_degree_target"] = args.mesh_degree
    cfg["mesh_degree_min"] = max(1, args.mesh_degree - 2)
    cfg["mesh_degree_max"] = max(args.mesh_degree * 2, args.mesh_degree + 1)
    return cfg


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--gateways", type=int, default=12)
    ap.add_argument("--base-port", type=int, default=48151)
    ap.add_argument("--lanes", type=int, default=20, help="shared-memory lanes per coder; drives the tmpfs size")
    ap.add_argument("--forward-threshold", type=float, default=0.75, help="served forward_shard_threshold (f)")
    ap.add_argument("--shard-factor", type=int, default=16, help="served rlnc_shard_factor (k)")
    ap.add_argument("--publisher-multiplier", type=float, default=2.5, help="served publisher_shard_multiplier (p)")
    ap.add_argument("--mesh-degree", type=int, default=6, help="served mesh_degree_target (D)")
    ap.add_argument("--dir", default=os.path.dirname(os.path.abspath(__file__)))
    args = ap.parse_args()

    if args.gateways < 2:
        print("gen-stack.py: --gateways must be at least 2", file=sys.stderr)
        return 2
    if args.lanes < 1:
        print("gen-stack.py: --lanes must be at least 1", file=sys.stderr)
        return 2

    compose, shm_mib, lane_mib = render(args)
    with open(os.path.join(args.dir, "stack.yml"), "w", encoding="utf-8") as fh:
        fh.write(compose)

    cfg = served_config(args, os.path.join(args.dir, "dynamic-config.json"))
    with open(os.path.join(args.dir, "served-config.json"), "w", encoding="utf-8") as fh:
        json.dump(cfg, fh, indent=2)
        fh.write("\n")

    k = args.shard_factor
    n = math.ceil(args.publisher_multiplier * k)
    # A node forwards recoded symbols only once its rank strictly exceeds
    # int(k*f); the publisher round-robins n symbols over its mesh targets, so
    # the direct share below is what one of those targets receives.
    gate = int(k * args.forward_threshold)
    targets = min(args.mesh_degree, args.gateways - 1)
    print(f"gen-stack.py: {args.gateways} gateways, ports "
          f"{args.base_port}..{args.base_port + args.gateways - 1}")
    print(f"  coding      k={k} p={args.publisher_multiplier} n=ceil(p*k)={n} "
          f"f={args.forward_threshold} forwards above rank {gate}")
    print(f"  publisher   round-robins {n} symbols per chunk over min(D,P)={targets} targets "
          f"= {n / targets:.2f} each, {100.0 * n / targets / k:.1f}% of k")
    print(f"  memory      {args.lanes} lanes x {lane_mib // args.lanes} MiB = {lane_mib} MiB per coder, "
          f"tmpfs capped at {shm_mib} MiB, {args.gateways} coders "
          f"= {args.gateways * shm_mib / 1024:.1f} GiB ceiling / "
          f"{args.gateways * lane_mib / 1024:.1f} GiB touched")
    print(f"  containers  {2 * args.gateways + 4}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
