// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: getoptimum/optimum_gateway/service/relay/v1/relay.proto

package relay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lightweight response for both unary calls and streamed acks
type Code int32

const (
	// Default value, should not be used in practice.
	Code_CODE_UNSPECIFIED Code = 0
	// Success, no error.
	Code_CODE_OK Code = 1
	// Invalid argument, e.g. missing required field or invalid value.
	Code_CODE_INVALID_ARGUMENT Code = 2
	// Caller is not authorized to perform the requested operation.
	Code_CODE_UNAUTHORIZED Code = 3
	// Internal server error, e.g. database failure or unexpected exception.
	Code_CODE_INTERNAL Code = 4
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "CODE_OK",
		2: "CODE_INVALID_ARGUMENT",
		3: "CODE_UNAUTHORIZED",
		4: "CODE_INTERNAL",
	}
	Code_value = map[string]int32{
		"CODE_UNSPECIFIED":      0,
		"CODE_OK":               1,
		"CODE_INVALID_ARGUMENT": 2,
		"CODE_UNAUTHORIZED":     3,
		"CODE_INTERNAL":         4,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

// Request to submit the encrypted block bytes.
// Gateway computes SHA-256 of payload
type SubmitEncryptedBlockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Submit either a single block or a batch.
	Items         [][]byte `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitEncryptedBlockRequest) Reset() {
	*x = SubmitEncryptedBlockRequest{}
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitEncryptedBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitEncryptedBlockRequest) ProtoMessage() {}

func (x *SubmitEncryptedBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitEncryptedBlockRequest.ProtoReflect.Descriptor instead.
func (*SubmitEncryptedBlockRequest) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitEncryptedBlockRequest) GetItems() [][]byte {
	if x != nil {
		return x.Items
	}
	return nil
}

// Request to submit the decryption key and signature for a previously
// submitted encrypted block.
type SubmitDecryptionKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: SHA-256(encrypted_block) as defined above
	EncryptedBlockSha256 []byte `protobuf:"bytes,1,opt,name=encrypted_block_sha256,json=encryptedBlockSha256,proto3" json:"encrypted_block_sha256,omitempty"`
	// AES-128-GCM key for the block (unique per slot)
	DecryptionKey []byte `protobuf:"bytes,2,opt,name=decryption_key,json=decryptionKey,proto3" json:"decryption_key,omitempty"`
	// Proposer signature over the final SignedBeaconBlock
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDecryptionKeyRequest) Reset() {
	*x = SubmitDecryptionKeyRequest{}
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDecryptionKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDecryptionKeyRequest) ProtoMessage() {}

func (x *SubmitDecryptionKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDecryptionKeyRequest.ProtoReflect.Descriptor instead.
func (*SubmitDecryptionKeyRequest) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitDecryptionKeyRequest) GetEncryptedBlockSha256() []byte {
	if x != nil {
		return x.EncryptedBlockSha256
	}
	return nil
}

func (x *SubmitDecryptionKeyRequest) GetDecryptionKey() []byte {
	if x != nil {
		return x.DecryptionKey
	}
	return nil
}

func (x *SubmitDecryptionKeyRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Acknowledgement of a request, with optional error code and message.
type StreamAck struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=getoptimum.optimum_gateway.service.relay.v1.Code" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable context on failure
	// Present whenever known; allows clients to correlate subsequent key
	// submissions with the computed hash from encrypted_block submissions.
	EncryptedBlockSha256 []byte `protobuf:"bytes,3,opt,name=encrypted_block_sha256,json=encryptedBlockSha256,proto3" json:"encrypted_block_sha256,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *StreamAck) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_UNSPECIFIED
}

func (x *StreamAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamAck) GetEncryptedBlockSha256() []byte {
	if x != nil {
		return x.EncryptedBlockSha256
	}
	return nil
}

// Acknowledgement of a request, with optional error code and message.
type SubmitDecryptionKeyAck struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=getoptimum.optimum_gateway.service.relay.v1.Code" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable context on failure
	// Present whenever known; allows clients to correlate subsequent key
	// submissions with the computed hash from encrypted_block submissions.
	EncryptedBlockSha256 []byte `protobuf:"bytes,3,opt,name=encrypted_block_sha256,json=encryptedBlockSha256,proto3" json:"encrypted_block_sha256,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SubmitDecryptionKeyAck) Reset() {
	*x = SubmitDecryptionKeyAck{}
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDecryptionKeyAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDecryptionKeyAck) ProtoMessage() {}

func (x *SubmitDecryptionKeyAck) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDecryptionKeyAck.ProtoReflect.Descriptor instead.
func (*SubmitDecryptionKeyAck) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitDecryptionKeyAck) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_UNSPECIFIED
}

func (x *SubmitDecryptionKeyAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitDecryptionKeyAck) GetEncryptedBlockSha256() []byte {
	if x != nil {
		return x.EncryptedBlockSha256
	}
	return nil
}

// Acknowledgement of a request, with optional error code and message.
type SubmitEncryptedBlockAck struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=getoptimum.optimum_gateway.service.relay.v1.Code" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable context on failure
	// Present whenever known; allows clients to correlate subsequent key
	// submissions with the computed hash from encrypted_block submissions.
	EncryptedBlockSha256 []byte `protobuf:"bytes,3,opt,name=encrypted_block_sha256,json=encryptedBlockSha256,proto3" json:"encrypted_block_sha256,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SubmitEncryptedBlockAck) Reset() {
	*x = SubmitEncryptedBlockAck{}
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitEncryptedBlockAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitEncryptedBlockAck) ProtoMessage() {}

func (x *SubmitEncryptedBlockAck) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitEncryptedBlockAck.ProtoReflect.Descriptor instead.
func (*SubmitEncryptedBlockAck) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitEncryptedBlockAck) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_UNSPECIFIED
}

func (x *SubmitEncryptedBlockAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitEncryptedBlockAck) GetEncryptedBlockSha256() []byte {
	if x != nil {
		return x.EncryptedBlockSha256
	}
	return nil
}

// Stream envelope allowing the same commands to be sent over a bidi stream
type StreamCommandsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-provided identifier to correlate requests and acks over the stream
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Command to be executed by the gateway. Only one of the commands may be set per message.
	//
	// Types that are valid to be assigned to Command:
	//
	//	*StreamCommandsRequest_SubmitEncryptedBlock
	//	*StreamCommandsRequest_SubmitDecryptionKey
	Command       isStreamCommandsRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCommandsRequest) Reset() {
	*x = StreamCommandsRequest{}
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCommandsRequest) ProtoMessage() {}

func (x *StreamCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCommandsRequest.ProtoReflect.Descriptor instead.
func (*StreamCommandsRequest) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescGZIP(), []int{5}
}

func (x *StreamCommandsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamCommandsRequest) GetCommand() isStreamCommandsRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StreamCommandsRequest) GetSubmitEncryptedBlock() *SubmitEncryptedBlockRequest {
	if x != nil {
		if x, ok := x.Command.(*StreamCommandsRequest_SubmitEncryptedBlock); ok {
			return x.SubmitEncryptedBlock
		}
	}
	return nil
}

func (x *StreamCommandsRequest) GetSubmitDecryptionKey() *SubmitDecryptionKeyRequest {
	if x != nil {
		if x, ok := x.Command.(*StreamCommandsRequest_SubmitDecryptionKey); ok {
			return x.SubmitDecryptionKey
		}
	}
	return nil
}

type isStreamCommandsRequest_Command interface {
	isStreamCommandsRequest_Command()
}

type StreamCommandsRequest_SubmitEncryptedBlock struct {
	SubmitEncryptedBlock *SubmitEncryptedBlockRequest `protobuf:"bytes,2,opt,name=submit_encrypted_block,json=submitEncryptedBlock,proto3,oneof"`
}

type StreamCommandsRequest_SubmitDecryptionKey struct {
	SubmitDecryptionKey *SubmitDecryptionKeyRequest `protobuf:"bytes,3,opt,name=submit_decryption_key,json=submitDecryptionKey,proto3,oneof"`
}

func (*StreamCommandsRequest_SubmitEncryptedBlock) isStreamCommandsRequest_Command() {}

func (*StreamCommandsRequest_SubmitDecryptionKey) isStreamCommandsRequest_Command() {}

// Request a JWT suitable for calling the endpoints in gateway.
type GetAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessTokenRequest) Reset() {
	*x = GetAccessTokenRequest{}
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenRequest) ProtoMessage() {}

func (x *GetAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*GetAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescGZIP(), []int{6}
}

// Response to a GetAccessTokenRequest, containing the token and its expiration.
type GetAccessTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bearer token to be used in Authorization metadata.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Unix epoch seconds when the token expires.
	ExpiresAtUnix int64 `protobuf:"varint,2,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessTokenResponse) Reset() {
	*x = GetAccessTokenResponse{}
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenResponse) ProtoMessage() {}

func (x *GetAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*GetAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccessTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetAccessTokenResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

var File_getoptimum_optimum_gateway_service_relay_v1_relay_proto protoreflect.FileDescriptor

const file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDesc = "" +
	"\n" +
	"7getoptimum/optimum_gateway/service/relay/v1/relay.proto\x12+getoptimum.optimum_gateway.service.relay.v1\"3\n" +
	"\x1bSubmitEncryptedBlockRequest\x12\x14\n" +
	"\x05items\x18\x01 \x03(\fR\x05items\"\x97\x01\n" +
	"\x1aSubmitDecryptionKeyRequest\x124\n" +
	"\x16encrypted_block_sha256\x18\x01 \x01(\fR\x14encryptedBlockSha256\x12%\n" +
	"\x0edecryption_key\x18\x02 \x01(\fR\rdecryptionKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\xa2\x01\n" +
	"\tStreamAck\x12E\n" +
	"\x04code\x18\x01 \x01(\x0e21.getoptimum.optimum_gateway.service.relay.v1.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x16encrypted_block_sha256\x18\x03 \x01(\fR\x14encryptedBlockSha256\"\xaf\x01\n" +
	"\x16SubmitDecryptionKeyAck\x12E\n" +
	"\x04code\x18\x01 \x01(\x0e21.getoptimum.optimum_gateway.service.relay.v1.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x16encrypted_block_sha256\x18\x03 \x01(\fR\x14encryptedBlockSha256\"\xb0\x01\n" +
	"\x17SubmitEncryptedBlockAck\x12E\n" +
	"\x04code\x18\x01 \x01(\x0e21.getoptimum.optimum_gateway.service.relay.v1.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x16encrypted_block_sha256\x18\x03 \x01(\fR\x14encryptedBlockSha256\"\xc3\x02\n" +
	"\x15StreamCommandsRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x80\x01\n" +
	"\x16submit_encrypted_block\x18\x02 \x01(\v2H.getoptimum.optimum_gateway.service.relay.v1.SubmitEncryptedBlockRequestH\x00R\x14submitEncryptedBlock\x12}\n" +
	"\x15submit_decryption_key\x18\x03 \x01(\v2G.getoptimum.optimum_gateway.service.relay.v1.SubmitDecryptionKeyRequestH\x00R\x13submitDecryptionKeyB\t\n" +
	"\acommand\"\x17\n" +
	"\x15GetAccessTokenRequest\"V\n" +
	"\x16GetAccessTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12&\n" +
	"\x0fexpires_at_unix\x18\x02 \x01(\x03R\rexpiresAtUnix*n\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCODE_OK\x10\x01\x12\x19\n" +
	"\x15CODE_INVALID_ARGUMENT\x10\x02\x12\x15\n" +
	"\x11CODE_UNAUTHORIZED\x10\x03\x12\x11\n" +
	"\rCODE_INTERNAL\x10\x042\x95\x05\n" +
	"\x15PrePropagationService\x12\x99\x01\n" +
	"\x0eGetAccessToken\x12B.getoptimum.optimum_gateway.service.relay.v1.GetAccessTokenRequest\x1aC.getoptimum.optimum_gateway.service.relay.v1.GetAccessTokenResponse\x12\xa6\x01\n" +
	"\x14SubmitEncryptedBlock\x12H.getoptimum.optimum_gateway.service.relay.v1.SubmitEncryptedBlockRequest\x1aD.getoptimum.optimum_gateway.service.relay.v1.SubmitEncryptedBlockAck\x12\xa3\x01\n" +
	"\x13SubmitDecryptionKey\x12G.getoptimum.optimum_gateway.service.relay.v1.SubmitDecryptionKeyRequest\x1aC.getoptimum.optimum_gateway.service.relay.v1.SubmitDecryptionKeyAck\x12\x90\x01\n" +
	"\x0eStreamCommands\x12B.getoptimum.optimum_gateway.service.relay.v1.StreamCommandsRequest\x1a6.getoptimum.optimum_gateway.service.relay.v1.StreamAck(\x010\x01B9Z7github.com/getoptimum/optimum-gateway/pkg/service/relayb\x06proto3"

var (
	file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescOnce sync.Once
	file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescData []byte
)

func file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescGZIP() []byte {
	file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescOnce.Do(func() {
		file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDesc), len(file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDesc)))
	})
	return file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDescData
}

var file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_goTypes = []any{
	(Code)(0),                           // 0: getoptimum.optimum_gateway.service.relay.v1.Code
	(*SubmitEncryptedBlockRequest)(nil), // 1: getoptimum.optimum_gateway.service.relay.v1.SubmitEncryptedBlockRequest
	(*SubmitDecryptionKeyRequest)(nil),  // 2: getoptimum.optimum_gateway.service.relay.v1.SubmitDecryptionKeyRequest
	(*StreamAck)(nil),                   // 3: getoptimum.optimum_gateway.service.relay.v1.StreamAck
	(*SubmitDecryptionKeyAck)(nil),      // 4: getoptimum.optimum_gateway.service.relay.v1.SubmitDecryptionKeyAck
	(*SubmitEncryptedBlockAck)(nil),     // 5: getoptimum.optimum_gateway.service.relay.v1.SubmitEncryptedBlockAck
	(*StreamCommandsRequest)(nil),       // 6: getoptimum.optimum_gateway.service.relay.v1.StreamCommandsRequest
	(*GetAccessTokenRequest)(nil),       // 7: getoptimum.optimum_gateway.service.relay.v1.GetAccessTokenRequest
	(*GetAccessTokenResponse)(nil),      // 8: getoptimum.optimum_gateway.service.relay.v1.GetAccessTokenResponse
}
var file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_depIdxs = []int32{
	0, // 0: getoptimum.optimum_gateway.service.relay.v1.StreamAck.code:type_name -> getoptimum.optimum_gateway.service.relay.v1.Code
	0, // 1: getoptimum.optimum_gateway.service.relay.v1.SubmitDecryptionKeyAck.code:type_name -> getoptimum.optimum_gateway.service.relay.v1.Code
	0, // 2: getoptimum.optimum_gateway.service.relay.v1.SubmitEncryptedBlockAck.code:type_name -> getoptimum.optimum_gateway.service.relay.v1.Code
	1, // 3: getoptimum.optimum_gateway.service.relay.v1.StreamCommandsRequest.submit_encrypted_block:type_name -> getoptimum.optimum_gateway.service.relay.v1.SubmitEncryptedBlockRequest
	2, // 4: getoptimum.optimum_gateway.service.relay.v1.StreamCommandsRequest.submit_decryption_key:type_name -> getoptimum.optimum_gateway.service.relay.v1.SubmitDecryptionKeyRequest
	7, // 5: getoptimum.optimum_gateway.service.relay.v1.PrePropagationService.GetAccessToken:input_type -> getoptimum.optimum_gateway.service.relay.v1.GetAccessTokenRequest
	1, // 6: getoptimum.optimum_gateway.service.relay.v1.PrePropagationService.SubmitEncryptedBlock:input_type -> getoptimum.optimum_gateway.service.relay.v1.SubmitEncryptedBlockRequest
	2, // 7: getoptimum.optimum_gateway.service.relay.v1.PrePropagationService.SubmitDecryptionKey:input_type -> getoptimum.optimum_gateway.service.relay.v1.SubmitDecryptionKeyRequest
	6, // 8: getoptimum.optimum_gateway.service.relay.v1.PrePropagationService.StreamCommands:input_type -> getoptimum.optimum_gateway.service.relay.v1.StreamCommandsRequest
	8, // 9: getoptimum.optimum_gateway.service.relay.v1.PrePropagationService.GetAccessToken:output_type -> getoptimum.optimum_gateway.service.relay.v1.GetAccessTokenResponse
	5, // 10: getoptimum.optimum_gateway.service.relay.v1.PrePropagationService.SubmitEncryptedBlock:output_type -> getoptimum.optimum_gateway.service.relay.v1.SubmitEncryptedBlockAck
	4, // 11: getoptimum.optimum_gateway.service.relay.v1.PrePropagationService.SubmitDecryptionKey:output_type -> getoptimum.optimum_gateway.service.relay.v1.SubmitDecryptionKeyAck
	3, // 12: getoptimum.optimum_gateway.service.relay.v1.PrePropagationService.StreamCommands:output_type -> getoptimum.optimum_gateway.service.relay.v1.StreamAck
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_init() }
func file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_init() {
	if File_getoptimum_optimum_gateway_service_relay_v1_relay_proto != nil {
		return
	}
	file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes[5].OneofWrappers = []any{
		(*StreamCommandsRequest_SubmitEncryptedBlock)(nil),
		(*StreamCommandsRequest_SubmitDecryptionKey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDesc), len(file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_goTypes,
		DependencyIndexes: file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_depIdxs,
		EnumInfos:         file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_enumTypes,
		MessageInfos:      file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_msgTypes,
	}.Build()
	File_getoptimum_optimum_gateway_service_relay_v1_relay_proto = out.File
	file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_goTypes = nil
	file_getoptimum_optimum_gateway_service_relay_v1_relay_proto_depIdxs = nil
}
