// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: getoptimum/optimum_gateway/service/aggregator/v1/aggregator.proto

package aggregator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Container groups encoded messages by gossip topic.
type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          [][]byte               `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDescGZIP(), []int{0}
}

func (x *Container) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Container) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// AttestationItem describes one attester contribution inside a packed attestation.
type AttestationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitteeId   uint64                 `protobuf:"varint,1,opt,name=committee_id,json=committeeId,proto3" json:"committee_id,omitempty"`
	AttesterIndex uint64                 `protobuf:"varint,2,opt,name=attester_index,json=attesterIndex,proto3" json:"attester_index,omitempty"`
	TopicIndex    uint32                 `protobuf:"varint,3,opt,name=topic_index,json=topicIndex,proto3" json:"topic_index,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationItem) Reset() {
	*x = AttestationItem{}
	mi := &file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationItem) ProtoMessage() {}

func (x *AttestationItem) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationItem.ProtoReflect.Descriptor instead.
func (*AttestationItem) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDescGZIP(), []int{1}
}

func (x *AttestationItem) GetCommitteeId() uint64 {
	if x != nil {
		return x.CommitteeId
	}
	return 0
}

func (x *AttestationItem) GetAttesterIndex() uint64 {
	if x != nil {
		return x.AttesterIndex
	}
	return 0
}

func (x *AttestationItem) GetTopicIndex() uint32 {
	if x != nil {
		return x.TopicIndex
	}
	return 0
}

func (x *AttestationItem) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// AttestationPack contains one unique attestation payload and all matching attesters.
type AttestationPack struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AttestationSszData []byte                 `protobuf:"bytes,1,opt,name=attestation_ssz_data,json=attestationSszData,proto3" json:"attestation_ssz_data,omitempty"`
	Items              []*AttestationItem     `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	SendTsMs           int64                  `protobuf:"varint,3,opt,name=send_ts_ms,json=sendTsMs,proto3" json:"send_ts_ms,omitempty"` // unix millis when the sending gateway emitted this pack
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttestationPack) Reset() {
	*x = AttestationPack{}
	mi := &file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationPack) ProtoMessage() {}

func (x *AttestationPack) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationPack.ProtoReflect.Descriptor instead.
func (*AttestationPack) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDescGZIP(), []int{2}
}

func (x *AttestationPack) GetAttestationSszData() []byte {
	if x != nil {
		return x.AttestationSszData
	}
	return nil
}

func (x *AttestationPack) GetItems() []*AttestationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AttestationPack) GetSendTsMs() int64 {
	if x != nil {
		return x.SendTsMs
	}
	return 0
}

// Msg is an aggregated batch emitted by the gateway.
type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tms           int64                  `protobuf:"varint,1,opt,name=tms,proto3" json:"tms,omitempty"` // unix millis
	Container     []*Container           `protobuf:"bytes,2,rep,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDescGZIP(), []int{3}
}

func (x *Msg) GetTms() int64 {
	if x != nil {
		return x.Tms
	}
	return 0
}

func (x *Msg) GetContainer() []*Container {
	if x != nil {
		return x.Container
	}
	return nil
}

var File_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto protoreflect.FileDescriptor

const file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDesc = "" +
	"\n" +
	"Agetoptimum/optimum_gateway/service/aggregator/v1/aggregator.proto\x120getoptimum.optimum_gateway.service.aggregator.v1\"5\n" +
	"\tContainer\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x02 \x03(\fR\x04data\"\x9a\x01\n" +
	"\x0fAttestationItem\x12!\n" +
	"\fcommittee_id\x18\x01 \x01(\x04R\vcommitteeId\x12%\n" +
	"\x0eattester_index\x18\x02 \x01(\x04R\rattesterIndex\x12\x1f\n" +
	"\vtopic_index\x18\x03 \x01(\rR\n" +
	"topicIndex\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xba\x01\n" +
	"\x0fAttestationPack\x120\n" +
	"\x14attestation_ssz_data\x18\x01 \x01(\fR\x12attestationSszData\x12W\n" +
	"\x05items\x18\x02 \x03(\v2A.getoptimum.optimum_gateway.service.aggregator.v1.AttestationItemR\x05items\x12\x1c\n" +
	"\n" +
	"send_ts_ms\x18\x03 \x01(\x03R\bsendTsMs\"r\n" +
	"\x03Msg\x12\x10\n" +
	"\x03tms\x18\x01 \x01(\x03R\x03tms\x12Y\n" +
	"\tcontainer\x18\x02 \x03(\v2;.getoptimum.optimum_gateway.service.aggregator.v1.ContainerR\tcontainerB>Z<github.com/getoptimum/optimum-gateway/pkg/service/aggregatorb\x06proto3"

var (
	file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDescOnce sync.Once
	file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDescData []byte
)

func file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDescGZIP() []byte {
	file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDescOnce.Do(func() {
		file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDesc), len(file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDesc)))
	})
	return file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDescData
}

var file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_goTypes = []any{
	(*Container)(nil),       // 0: getoptimum.optimum_gateway.service.aggregator.v1.Container
	(*AttestationItem)(nil), // 1: getoptimum.optimum_gateway.service.aggregator.v1.AttestationItem
	(*AttestationPack)(nil), // 2: getoptimum.optimum_gateway.service.aggregator.v1.AttestationPack
	(*Msg)(nil),             // 3: getoptimum.optimum_gateway.service.aggregator.v1.Msg
}
var file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_depIdxs = []int32{
	1, // 0: getoptimum.optimum_gateway.service.aggregator.v1.AttestationPack.items:type_name -> getoptimum.optimum_gateway.service.aggregator.v1.AttestationItem
	0, // 1: getoptimum.optimum_gateway.service.aggregator.v1.Msg.container:type_name -> getoptimum.optimum_gateway.service.aggregator.v1.Container
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_init() }
func file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_init() {
	if File_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDesc), len(file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_goTypes,
		DependencyIndexes: file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_depIdxs,
		MessageInfos:      file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_msgTypes,
	}.Build()
	File_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto = out.File
	file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_goTypes = nil
	file_getoptimum_optimum_gateway_service_aggregator_v1_aggregator_proto_depIdxs = nil
}
